name: Sync GitHub with ADO

on:
  workflow_dispatch:
  issue_comment:
    types: [ labeled ]
  issues:
    types: [ labeled ]

jobs:
  build:
    name: Run gh-sync from Pipeline
    if: ${{ github.event.label.name == 'ado-sync' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger gh-sync'
        uses: Azure/pipelines@releases/v1
        with:
          azure-devops-project-url: 'https://ms-quantum.visualstudio.com/Sandbox'
          azure-pipeline-name: 'gh-sync' 
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
