name: Sync GitHub with ADO

on: 
  issues:
    types: [closed, edited, deleted, reopened, assigned, unassigned, labeled, unlabeled]
  issue_comment:
  push:
    branches:
      - imiles/task-37413

jobs:
  build:
    name: Run gh-sync from Pipeline
#     if: ${{ github.event.label.name == 'ado-sync' || contains(github.event.issue.labels.*.name, 'ado-sync') }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - id: AzureKeyVault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: 'kv-qdk-build'
          secrets: 'qdkBuildPAT'
          
      - name: 'Trigger gh-sync'
        uses: Azure/pipelines@releases/v1
        with:
          azure-devops-project-url: 'https://ms-quantum.visualstudio.com/ms-quantum/Quantum Program'
          azure-pipeline-name: 'gh-sync' 
          azure-devops-token: ${{ steps.AzureKeyVault.outputs.qdkBuildPAT }}
          azure-pipeline-variables: "{'issueNumber': ${{github.event.issue.number}}, 'repoName': 'QuantumKatas' }"
